import { Component } from '@angular/core';

@Component({
  selector: 'app-loss-analysis',
  templateUrl: './loss-analysis.component.html',
  styleUrls: ['./loss-analysis.component.scss']
})
export class LossAnalysisComponent {
  public columns: any =[
    {
      field: "Id",
      title: "",
      width:40,
      type: "checkbox",
      columnmenu:false,
      filterable : false,
      sortable:false
    },
    {
      field: 'alerts',
      title: 'Alerts',
      type: 'alerts',
      columnmenu:false,
      sortable: false,
      groupable: true,
    },
    {
      field: "SubmissionID",
      format: "{0:c}",
      title: "Submission ID",
      width:180,
      type: "link",
      sortable:true,
      columnmenu:true,
    },
    {
        field: "AccountName",
        title: "Account Name",
        type: "text",
        sortable:false,
        columnmenu:true,
      },
      {
        field: "EffectiveDate",
        format: "{0:c}",
        title: "Effective Date",
        type: "text",
        sortable:true,
        columnmenu:true,
      },
      {
        field: "Type",
        format: "{0:c}",
        title: "Type",
        type: "text",
        sortable:true,
        columnmenu:true,
      },
    {
        field: "AgencyName",
        title: "Agency Name",
        type: "text",
        sortable:false,
        columnmenu:true,
      },
      {
        field: "LOB",
        format: "{0:c}",
        title: "LOB",
        type: "text",
        sortable:true,
        columnmenu:true,
      },
      {
        field: "Priority",
        format: "{0:c}",
        title: "Priority",
        type: "text",
        sortable:true,
        columnmenu:true,
      },
      {
        field: "Status",
        format: "{0:c}",
        title: "Status",
        type: "text",
        sortable:true,
        columnmenu:true,
      },
      {
        field: "AssignedBy",
        format: "{0:c}",
        title: "Assigned By",
        type: "text",
        sortable:true,
        columnmenu:true,
      }
  ];
   public tableData: any[]= 
   [
    {
      Id: "1",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "2",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "3",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "4",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "5",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "6",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "7",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "8",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "9",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "10",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "11",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "12",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "13",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "14",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "15",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "16",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "17",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "18",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    },
    {
      Id: "19",
      SubmissionID: "B143-03312302301",
      AccountName: "Dante Mason",
      EffectiveDate: "03/01/2023",
      Type: "New Business",
      AgencyName: "ACE Insurance",
      LOB: "Property",
      Priority: "High",
      Status : "AutoApproved",
      AssignedBy: "Auto Assigned",
    },
    {
      Id: "20",
      SubmissionID: "B143-03312302302",
      AccountName: "Duke & Duke",
      EffectiveDate: "04/01/2023",
      Type: "Renewal",
      AgencyName: "Welch Ins Agency",
      LOB: "Property,GL, WC",
      Priority: "Low",
      Status : "ExtractionException",
      AssignedBy: "John Williams",
    }
  ];
}
