import { Component } from '@angular/core';

@Component({
  selector: 'app-exposer-analysis',
  templateUrl: './exposer-analysis.component.html',
  styleUrls: ['./exposer-analysis.component.scss']
})
export class ExposerAnalysisComponent {

  public columns: any =[
    {
      field: "LocationNumber",
      title: "loc#",
      width:40,
      type: "text",
      columnmenu:true,
      filterable : true,
      sortable:true
    },
    // {
    //   field: 'alerts',
    //   title: 'Alerts',
    //   type: 'alerts',
    //   columnmenu:false,
    //   sortable: false,
    //   groupable: true,
    // },
    {
      field: "BuildingNumber",
      // format: "{0:c}",
      title: "Bidg#",
      width:150,
      type: "text",
      sortable:true,
      filterable : true,
      columnmenu:true,
    },
    {
        field: "BuildingName",
        title: "Building Name",
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "FullAddress",
        // format: "{0:c}",
        title: "Full Address",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "YearBuilt",
        // format: "{0:c}",
        title: "Year Built",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
    {
        field: "TotalArea",
        title: "Total Area",
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "RootType",
        // format: "{0:c}",
        title: "Root Type",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "NumberOfStories",
        // format: "{0:c}",
        title: "# Of Stories",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "TIV",
        // format: "{0:c}",
        title: "TIV",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Geolocation",
        // format: "{0:c}",
        title: "Geolocation",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Flood",
        // format: "{0:c}",
        title: "Flood",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Earthquake",
        // format: "{0:c}",
        title: "Earthquake",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "NamedStorm",
        // format: "{0:c}",
        title: "Named Storm",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Hail",
        // format: "{0:c}",
        title: "Hail",
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      }
  ];
   public tableData: any[]= 
   [
    {
      LocationNumber: "1",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "2",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "3",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "4",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "5",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "6",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "7",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "8",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "9",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "10",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "11",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "12",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "13",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "14",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "15",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "16",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "17",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "18",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    },
    {
      LocationNumber: "19",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    }, 
    {
      LocationNumber: "20",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
    }
  ];
}
