import { Component } from '@angular/core';
import { SelectEvent } from '@progress/kendo-angular-layout';
@Component({
  selector: 'app-exposer-analysis',
  templateUrl: './exposer-analysis.component.html',
  styleUrls: ['./exposer-analysis.component.scss']
})
export class ExposerAnalysisComponent {
  public onTabSelect(e: SelectEvent): void {
  }
  public columns: any =[
    {
      field: "LocationNumber",
      title: "loc#",
      width:120,
      type: "text",
      columnmenu:true,
      filterable : true,
      sortable:true
    },
    // {
    //   field: 'alerts',
    //   title: 'Alerts',
    //   type: 'alerts',
    //   columnmenu:false,
    //   sortable: false,
    //   groupable: true,
    // },
    {
      field: "BuildingNumber",
      // format: "{0:c}",
      title: "Bidg#",
      width:160,
      type: "text",
      sortable:true,
      filterable : true,
      columnmenu:true,
    },
    {
        field: "BuildingName",
        title: "Building Name",
        width:200,
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "FullAddress",
        // format: "{0:c}",
        title: "Full Address",
        width:350,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "YearBuilt",
        // format: "{0:c}",
        title: "Year Built",
        width:170,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
    {
        field: "TotalArea",
        title: "Total Area",
        width:160,
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "RootType",
        // format: "{0:c}",
        title: "Root Type",
        width:160,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "NumberOfStories",
        // format: "{0:c}",
        title: "# Of Stories",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "TIV",
        // format: "{0:c}",
        title: "TIV",
        width:130,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Geolocation",
        // format: "{0:c}",
        title: "Geolocation",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Flood",
        // format: "{0:c}",
        title: "Flood",
        width:150,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Earthquake",
        // format: "{0:c}",
        title: "Earthquake",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "NamedStorm",
        // format: "{0:c}",
        title: "Named Storm",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Hail",
        // format: "{0:c}",
        title: "Hail",
        width:150,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
      field: "RoofAge",
      // format: "{0:c}",
      title: "Roof Age",
      width:180,
      type: "text",
      sortable:true,
      columnmenu:true,
      filterable : true,
    },
    {
    field: "Construction",
    // format: "{0:c}",
    title: "Construction",
    width:180,
    type: "text",
    sortable:true,
    columnmenu:true,
    filterable : true,
  },
{
    field: "Occupancy",
  // format: "{0:c}",
  title: "Occupancy",
  width:180,
  type: "text",
  sortable:true,
  columnmenu:true,
  filterable : true,
},
{
  field: "Protection",
// format: "{0:c}",
title: "Protection",
width:180,
type: "text",
sortable:true,
columnmenu:true,
filterable : true,
},
{
  field: "Wiring",
// format: "{0:c}",
title: "Wiring",
width:150,
type: "text",
sortable:true,
columnmenu:true,
filterable : true,
},
{
  field: "Sprinkler",
// format: "{0:c}",
title: "Sprinkler",
width:150,
type: "text",
sortable:true,
columnmenu:true,
filterable : true,
},
{
  field: "FireAlarm",
// format: "{0:c}",
title: "Fire Alarm",
width:180,
type: "text",
sortable:true,
columnmenu:true,
filterable : true,
}
  ];


   public tableData: any[]= 
   [
    {
      LocationNumber: "1",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "2",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "3",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "4",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "5",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "6",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "7",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "8",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "9",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "10",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "11",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "12",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "13",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "14",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "15",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "16",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "17",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "18",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    },
    {
      LocationNumber: "19",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    }, 
    {
      LocationNumber: "20",
      BuildingNumber: "B143-03312302301",
      BuildingName: "Summer Sea CAI",
      FullAddress: "88500 US Highway OneTavernier FL 33070",
      YearBuilt: "1976",
      TotalArea: "3200",
      RootType: "Flat",
      NumberOfStories: "1",
      TIV : "$ 21,111,924",
      Geolocation: "42.536457, -70.985786",
      Flood:"Low",
      Earthquake:"Medium",
      NamedStorm:"Low",
      Hail:"High",
      RoofAge:"",
      Construction:"1",
      Occupancy:"",
      Protection:"1",
      Wiring:"High Risk",
      Sprinkler:"90%",
      FireAlarm:"",
    }
  ];
}
