export interface Submission {
    LocationNumber: string,
    BuildingNumber: string,
    BuildingName: string,
    FullAddress: string,
    YearBuilt: string,
    TotalArea: string,
    RootType: string,
    NumberOfStories: string,
    TIV : string,
    Geolocation: string,
    Flood:string,
    Earthquake:string,
    NamedStorm:string,
    Hail:string,
    RoofAge:string,
    Construction:string,
    Occupancy:string,
    Protection:string,
    Wiring:string,
    Sprinkler:string,
    FireAlarm:string,
  }