import { Component } from '@angular/core';
import { SelectEvent } from '@progress/kendo-angular-layout';

@Component({
  selector: 'app-application',
  templateUrl: './application.component.html',
  styleUrls: ['./application.component.scss']
})
export class ApplicationComponent {
  public onTabSelect(e: SelectEvent): void {
    console.log(e);
  }



  public columns: any =[
    {
      field: "ClaimNo",
      title: "Claim No.",
      width:160,
      type: "text",
      columnmenu:true,
      filterable : true,
      sortable:true
    },
    // {
    //   field: 'alerts',
    //   title: 'Alerts',
    //   type: 'alerts',
    //   columnmenu:false,
    //   sortable: false,
    //   groupable: true,
    // },
    {
      field: "PolicyEffectiveDate",
      // format: "{0:c}",
      title: "Policy Effective Date",
      width:250,
      type: "text",
      sortable:true,
      filterable : true,
      columnmenu:true,
    },
    {
        field: "LineOfBusiness",
        title: "Line of Business",
        width:220,
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "LossDate",
        // format: "{0:c}",
        title: "Loss Date",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ClaimReportDate",
        // format: "{0:c}",
        title: "Claim Report Date",
        width:220,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
    {
        field: "LossLocation",
        title: "Loss Location",
        width:200,
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "LossState",
        // format: "{0:c}",
        title: "Loss State",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Carrier",
        // format: "{0:c}",
        title: "Carrier",
        width:150,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "PolicyNo",
        // format: "{0:c}",
        title: "Policy No.",
        width:150,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ClaimantName",
        // format: "{0:c}",
        title: "Claimant Name",
        width:220,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ClaimDescription",
        // format: "{0:c}",
        title: "Claim Description",
        width:270,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ClaimStatus",
        // format: "{0:c}",
        title: "Claim Status",
        type: "text",
        width:180,
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ValuationDate",
        // format: "{0:c}",
        title: "Valuation Date",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "IndemnityRes",
        // format: "{0:c}",
        title: "Indemnity Res.",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ExpenseRes",
        // format: "{0:c}",
        title: "Expense Res.",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "IndemnityPaid",
        // format: "{0:c}",
        title: "Indemnity Paid",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ExpensePaid",
        // format: "{0:c}",
        title: "Expense Paid",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "TotalIncurred",
        // format: "{0:c}",
        title: "Total Incurred",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      }
  ];
   public tableData: any[]= 
   [
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    },
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    }, 
    {
      ClaimNo: "1900918971",
      PolicyEffectiveDate: "4/1/2020",
      LineOfBusiness: "Proeprty",
      LossDate: "08/11/2021",
      ClaimReportDate:"08/16/2021",
      LossLocation:"88500 US Highway OneTavernier FL 33070",
      LossState:"NY",
      Carrier: "Travelers",
      PolicyNo: "6043467853",
      ClaimantName: "Leonard Stiles",
      ClaimDescription: "Claimant alleges an insured tree fell on his property during a recentstorm, damaging a shed",
      ClaimStatus : "Closed",
      ValuationDate: "05/07/22",
      IndemnityRes:"$0.00",
      ExpenseRes:"$0.00",
      IndemnityPaid:"$0.00",
      ExpensePaid:"$0",
      TotalIncurred:"$0.00"
    }
  ];



  public columns1: any =[
    {
      field: "LocNumber",
      title: "Loc #",
      width:150,
      type: "text",
      columnmenu:true,
      filterable : true,
      sortable:true
    },
    // {
    //   field: 'alerts',
    //   title: 'Alerts',
    //   type: 'alerts',
    //   columnmenu:false,
    //   sortable: false,
    //   groupable: true,
    // },
    {
      field: "BldgNumber",
      // format: "{0:c}",
      title: "Bldg #",
      width:180,
      type: "text",
      sortable:true,
      filterable : true,
      columnmenu:true,
    },
    {
        field: "BldgNameAndOccupancy",
        title: "Bldg Name & Occupancy",
        width:280,
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Address",
        // format: "{0:c}",
        title: "Address",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "City",
        // format: "{0:c}",
        title: "City",
        width:150,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
    {
        field: "State",
        title: "State",
        width:140,
        type: "text",
        sortable:false,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ZipCode",
        // format: "{0:c}",
        title: "Zip Code",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Coinsurance",
        // format: "{0:c}",
        title: "Coinsurance",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Valuation",
        // format: "{0:c}",
        title: "Valuation",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Building",
        // format: "{0:c}",
        title: "Building",
        width:180,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "BPP",
        // format: "{0:c}",
        title: "BPP",
        width:150,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "BusinessIncome",
        // format: "{0:c}",
        title: "Business Income",
        type: "text",
        width:250,
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ExtraExpense",
        // format: "{0:c}",
        title: "Extra Expense",
        width:250,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Contents",
        // format: "{0:c}",
        title: "Contents",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "PersonalPropertyofOthers",
        // format: "{0:c}",
        title: "Personal Property of Others",
        width:330,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Others",
        // format: "{0:c}",
        title: "Others",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "ISOConstructionType",
        // format: "{0:c}",
        title: "ISO Construction Type",
        width:280,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "TotalArea",
        // format: "{0:c}",
        title: "Total Area(sq feet)",
        width:250,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "NoOfStories",
        // format: "{0:c}",
        title: "# of Stories",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "AlarmType",
        // format: "{0:c}",
        title: "Alarm Type",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "YearBuilt",
        // format: "{0:c}",
        title: "Year Built",
        width:200,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "Sprinkler",
        // format: "{0:c}",
        title: "Sprinkler(Yes/No)",
        width:250,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
      {
        field: "TotalInsuredValues",
        // format: "{0:c}",
        title: "Total Insured Values",
        width:280,
        type: "text",
        sortable:true,
        columnmenu:true,
        filterable : true,
      },
  ];
   public tableData1: any[]= 
   [
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    },
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    }, 
    {
      LocNumber: "1",
      BldgNumber: "1",
      BldgNameAndOccupancy: "Summer Sea CAI",
      Address: "88500 US Highway",
      City:"OneTavernier",
      State:"FL",
      ZipCode:"33070",
      Coinsurance: "80%",
      Valuation: "RC",
      Building: "$1,000,000",
      BPP: "$500,000",
      BusinessIncome : "$1,000,000",
      ExtraExpense: "",
      Contents:"",
      PersonalPropertyofOthers:"",
      Others:"",
      ISOConstructionType:"Flat",
      TotalArea:"3200",
      NoOfStories:"1",
      AlarmType:"",
      YearBuilt:"1976",
      Sprinkler:"Yes",
      TotalInsuredValues:"$ 2,500,000",
    }
  ];



}
